[project]
name = "codecrafters-kafka"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "loguru==0.7.3"
]

[tool.uv]
exclude-newer = "1 week"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "kafka-python>=2.3.1",
    "mypy>=1.20.2",
    "pytest>=9.0.3",
    "ruff>=0.15.1",
]
